### ISSUE TITLE
SPMySQLFramework no longer builds with Xcode 9.1

### ISSUE THREAD

**Issue by alex-techlab** [sequelpro/sequelpro#2920]
I'm trying to integrate the SPMySQLFramework into a Swift project, but ever since I upgraded to Xcode 9.1, for some reason it won't build anymore. 

This used to work with Xcode 8.3.3 but after upgrading I get about 17 errors like:

For example In SPMySQLConstants.h:
at line 63: `Declaration of 'NSUInteger' must be imported from module 'ObjectiveC.NSObjCRuntime' before it is required`
at line 79: `Parameter name omitted`
at line 80: `Use of undeclared identifier 'SPMySQLClientFlagCompression`
and so on...

- I integrated (dragged) the "SPMySQLFramework.xcodeproj" file into my project. 
- I made sure that the framework is present in both the "Embedded binaries" and "Linked Frameworks" sections in my project's "General" section 
- I also made sure that the framework is present in the "Build Phases" section (embed frameworks and link binary with libraries sections). 
- Also in my project's bridging header I have this line: #import "SPMySQL/SPMySQL.h"

**Comment by dmoagx** [comment]
I tried it with Xcode 9.2 beta and could build and run a Swift app, but I had to add `#import <Cocoa/Cocoa.h>` as first line in `SPMySQL.h`
